### ISSUE TITLE
ForbiddenError when executing and accessing server on browser

### ISSUE THREAD

**Issue by AxDSan** [thebearingedge/livereload-server-vscode#2]
Getting this error:

![image](https://github.com/thebearingedge/vscode-livereload-server/assets/1641797/388781e5-71d0-4431-88c7-ba53753f2c6d)

Log
```
ForbiddenError: Forbidden
	at c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:75:1983
	at xi.handle_request (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:2929)
	at g (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:8074)
	at c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:7668
	at Ft.process_params (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:8190)
	at x (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:7597)
	at W.<anonymous> (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:53:27985)
	at W.emit (node:events:513:28)
	at W.error (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:42:40337)
	at W.pipe (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:42:43222)
	at c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:53:27993
	at xi.handle_request (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:2929)
	at g (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:8074)
	at c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:7668
	at Ft.process_params (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:8190)
	at x (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:7597)
	at c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:94:2753
	at xi.handle_request (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:2929)
	at g (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:8074)
	at c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:7668
	at Ft.process_params (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:8190)
	at x (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:7597)
	at c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:10861
	at xi.handle_request (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:2929)
	at g (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:8074)
	at c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:7668
	at Ft.process_params (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:8190)
	at x (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:7597)
	at c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:11147
	at xi.handle_request (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:2929)
	at g (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:8074)
	at c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:7668
	at Ft.process_params (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:8190)
	at x (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:7597)
	at Ft.handle (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:38:6974)
	at ne.handle (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:53:479)
	at Server.t (c:\Users\Admin\.vscode\extensions\thebearingedge.livereload-server-0.2.6\dist\index.js:63:751)
	at Server.emit (node:events:525:35)
	at parserOnIncoming (node:_http_server:1072:12)
	at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

**Comment by thebearingedge** [comment]
Hi @AxDSan thanks for the report. If you try LiveServer (different extension) do you get the same error?

I've only tested on Mac/Linux directly and WSL2.

**Comment by thebearingedge** [comment]
Not sure if Admin is a special windows account with different permissions.

**Comment by AxDSan** [comment]
> Hi @AxDSan thanks for the report. If you try LiveServer (different extension) do you get the same error?
> 
> I've only tested on Mac/Linux directly and WSL2.

Hi there 👋, yes, I've used another similar extension (by Ritwick Dey), and it works just fine.

I'm using it on barebones Windows 11

**Comment by AxDSan** [comment]
> Not sure if Admin is a special windows account with different permissions.

Yes, not really, it's a plain old, Administrator's Windows account.

**Comment by AxDSan** [comment]
...also forgot to mention there's an error thrown at the browser console saying something about "document-src origin" or something like that? does that helps out?

I'm not using the laptop anymore, so can't give you the exact error, but will update this with the actual error when I get back go it later. if it helps 👌

**Comment by thebearingedge** [comment]
Thanks for the additional info! Are you getting the error when launching from an HTML file, a while directory, or both?

And lastly can you confirm the url that your browser is trying load?
